apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-gira
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-gira
    app.kubernetes.io/part-of: test-app-dxyy
  name: devfile-sample-hello-world-gira
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-gira
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-gira
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-fbql-tenant/test-app-dxyy/devfile-sample-hello-world-gira@sha256:bd952d92881e0c822c0fd0b99a1c62f5e27bdc8bf2cb789df89731db9bbf8541
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
